services:
  - type: web
    name: yt-dlp-downloader
    env: node
    region: oregon
    plan: free

    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: npm start

    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 3000
      - key: YTDLP_PATH
        value: yt-dlp
      - key: FFMPEG_PATH
        value: ./bin/ffmpeg
      - key: YTDLP_COOKIES_PATH
        value: ./cookies.txt
      - key: NODE_ENV
        value: production

